### ISSUE TITLE
Video capture support needs to be documented

### ISSUE THREAD

**Issue by hamishwillee** [Dronecode/csd_docs#22]
https://github.com/Dronecode/camera-streaming-daemon/pull/157#issuecomment-380711708

Actions:
* [x] UPdate to overview to say that MAVLink video capture is supported
* [x] Addition of vidcap information about [config file](https://hamishwillee.gitbooks.io/camera-streaming-daemon/content/en/guide/configuration_file.html) changes
* [x] Update sample file (@lbegani )

This is waiting on @lbegani for part 3.

**Comment by hamishwillee** [comment]
@lbegani Can we have an update of the sample config for vidcap (just like you did for imgcap)? See https://github.com/Dronecode/camera-streaming-daemon/pull/157/files#diff-c603ddb75c825043d7f21b6f2f8b3a36R12

**Comment by lbegani** [comment]
https://github.com/Dronecode/camera-streaming-daemon/pull/167

**Comment by hamishwillee** [comment]
Closing this. Will be addressed by #24
